//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arriendo
    {
        public int id_arriendo { get; set; }
        public int id_propiedad { get; set; }
        public int id_inquilino { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public decimal canon_mensual { get; set; }
        public Nullable<decimal> deposito { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual propiedad propiedad { get; set; }
    }
}
