//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class imagen_propiedad
    {
        public int id_Imagen { get; set; }
        public int id_propiedad { get; set; }
        public string Nombre { get; set; }


        [JsonIgnore]
        public virtual propiedad propiedad { get; set; }
    }
}
