//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INMOBILIARIAAEntities : DbContext
    {
        public INMOBILIARIAAEntities()
            : base("name=INMOBILIARIAAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arriendo> arriendoes { get; set; }
        public virtual DbSet<ciudad> ciudads { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<consignacion> consignacions { get; set; }
        public virtual DbSet<detalle_orden> detalle_orden { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<estado_propiedad> estado_propiedad { get; set; }
        public virtual DbSet<imagen_propiedad> imagen_propiedad { get; set; }
        public virtual DbSet<orden_compra> orden_compra { get; set; }
        public virtual DbSet<propiedad> propiedads { get; set; }
        public virtual DbSet<propiedad_modelo> propiedad_modelo { get; set; }
        public virtual DbSet<propietario> propietarios { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
        public virtual DbSet<proyecto> proyectoes { get; set; }
        public virtual DbSet<sede> sedes { get; set; }
        public virtual DbSet<tipo_propiedad> tipo_propiedad { get; set; }
        public virtual DbSet<tipo_proveedor> tipo_proveedor { get; set; }
        public virtual DbSet<tipo_visita> tipo_visita { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<visita> visitas { get; set; }
    }
}
