//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden_compra()
        {
            this.detalle_orden = new HashSet<detalle_orden>();
        }
    
        public int id_orden { get; set; }
        public int id_proveedor { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha_orden { get; set; }
        public decimal total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden> detalle_orden { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
