//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public propiedad()
        {
            this.arriendoes = new HashSet<arriendo>();
            this.consignacions = new HashSet<consignacion>();
            this.imagen_propiedad = new HashSet<imagen_propiedad>();
            this.ventas = new HashSet<venta>();
            this.visitas = new HashSet<visita>();
        }
    
        public int id_propiedad { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public int id_tipo_propiedad { get; set; }
        public Nullable<decimal> area_m2 { get; set; }
        public Nullable<int> habitaciones { get; set; }
        public Nullable<int> banos { get; set; }
        public Nullable<int> parqueaderos { get; set; }
        public Nullable<short> anio_construccion { get; set; }
        public string direccion { get; set; }
        public int id_ciudad { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> precio_arriendo { get; set; }
        public int id_estado_propiedad { get; set; }
        public System.DateTime fecha_registro { get; set; }


        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arriendo> arriendoes { get; set; }

        public virtual ciudad ciudad { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consignacion> consignacions { get; set; }

        [JsonIgnore]
        public virtual estado_propiedad estado_propiedad { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagen_propiedad> imagen_propiedad { get; set; }

        [JsonIgnore]
        public virtual propiedad_modelo propiedad_modelo { get; set; }

        [JsonIgnore]
        public virtual tipo_propiedad tipo_propiedad { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> ventas { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visita> visitas { get; set; }
    }
}
