//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class propiedad_modelo
    {
        public int id_propiedad { get; set; }
        public int id_proyecto { get; set; }
        public Nullable<decimal> costo_decoracion { get; set; }
        public Nullable<System.DateTime> fecha_decoracion { get; set; }


        [JsonIgnore]
        public virtual propiedad propiedad { get; set; }

        [JsonIgnore]
        public virtual proyecto proyecto { get; set; }
    }
}
