//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.orden_compra = new HashSet<orden_compra>();
        }
    
        public int id_proveedor { get; set; }
        public string nombre_comercial { get; set; }
        public string nit { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public int id_tipo_proveedor { get; set; }


        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_compra> orden_compra { get; set; }

        [JsonIgnore]
        public virtual tipo_proveedor tipo_proveedor { get; set; }
    }
}
