//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyecto()
        {
            this.propiedad_modelo = new HashSet<propiedad_modelo>();
        }
    
        public int id_proyecto { get; set; }
        public string nombre { get; set; }
        public int id_ciudad { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_lanzamiento { get; set; }
        public Nullable<System.DateTime> fecha_entrega_estimada { get; set; }
        public string desarrollador { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propiedad_modelo> propiedad_modelo { get; set; }
    }
}
