//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_WEB_INMOBILIARIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int id_venta { get; set; }
        public int id_propiedad { get; set; }
        public int id_cliente { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public decimal precio_final { get; set; }
        public decimal comision { get; set; }


        [JsonIgnore]
        public virtual cliente cliente { get; set; }


        [JsonIgnore]
        public virtual empleado empleado { get; set; }

        [JsonIgnore]
        public virtual propiedad propiedad { get; set; }
    }
}
